-   repo: git@git.yelpcorp.com:mirrors/pre-commit/pre-commit-hooks
    sha: d3db0385825d4c082bc7117c090ac16cb4840f3e
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
-   repo: git@git.yelpcorp.com:yelp_pre_commit_hooks
    sha: 593e30fc5782c91f2df2f03e86988375b5a60d8c
    hooks:
    -   id: stop-dollar-html
    -   id: httplib-https-connection
    -   id: use-except-as
    -   id: check_mock_methods
    -   id: byte_order_mark
    -   id: fix-encoding-pragma
    -   id: check-added-large-files
-   repo: git@git.yelpcorp.com:mirrors/asottile/reorder_python_imports
    sha: 04ab8446d0c82026e7d7b0c1ba96bab1cca8185e
    hooks:
    -   id: reorder-python-imports
        args: [
            '--add-import', 'from __future__ import absolute_import',
            '--add-import', 'from __future__ import unicode_literals',
        ]
