branches:
  only:
  - master
  - /^v[0-9.]+$/
language: python
services:
  - docker
python:
  - '2.7'
install: pip install coveralls tox
script: make -f Makefile-opensource test
after_success:
  - coveralls
