branches:
  only:
  - master
  - /^v[0-9.]+$/
language: python
services:
  - docker
python:
  - '2.7'
env:
  DOCKER_COMPOSE_VERSION: 1.4.2
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install: pip install coveralls tox
script: make -f Makefile-opensource test
after_success:
  - coveralls
