branches:
  only:
  - master
  - /^v[0-9.]+$/
language: python
services:
  - docker
python:
  - '2.7'
env:
  OPEN_SOURCE_MODE: true
  PULL_CONTAINERS: true
  FORCE_FRESH_CONTAINERS: true
install: pip install coveralls tox
script: make -f Makefile-opensource test
after_success:
  - coveralls
